"""
Default metadata configuration for APS 8-ID-I beamline.

This module defines the default metadata values used in NeXus files for
experiments at the APS 8-ID-I beamline. These values serve as templates
for various instrument parameters, sample information, and experimental
conditions.
"""

# populated list for the defaults used at 8IDI
default_metadata = {
    "/entry/beamline": "APS-8-ID-I",
    "/entry/scan_number": 1,
    "/entry/start_time": "2025-02-10 22:00:00.051404Z",
    "/entry/end_time": "2025-02-10 22:22:22.051404Z",
    "/entry/instrument/detector_1/beam_center_x": 512,
    "/entry/instrument/detector_1/beam_center_y": 512,
    "/entry/instrument/detector_1/beam_center_position_x": 1.0,
    "/entry/instrument/detector_1/beam_center_position_y": 1.0,
    "/entry/instrument/detector_1/position_x": 1.0,
    "/entry/instrument/detector_1/position_y": 1.0,
    "/entry/instrument/detector_1/count_time": 1.0,
    "/entry/instrument/detector_1/detector_name": "Eiger4m",
    "/entry/instrument/detector_1/distance": 12.0,
    "/entry/instrument/detector_1/frame_time": 1.0,
    "/entry/instrument/detector_1/x_pixel_size": 7.5e-05,
    "/entry/instrument/detector_1/y_pixel_size": 7.5e-05,
    "/entry/instrument/detector_1/rotation_x": 0.0,
    "/entry/instrument/detector_1/rotation_y": 0.0,
    "/entry/instrument/detector_1/rotation_z": 0.0,
    "/entry/instrument/detector_1/compression": "bslz4",
    "/entry/instrument/incident_beam/extent": 1e-06,
    "/entry/instrument/incident_beam/incident_energy": 12.0,
    "/entry/instrument/incident_beam/incident_energy_spread": 0.0001,
    "/entry/instrument/incident_beam/incident_polarization_type": "linear_horizontal",
    "/entry/instrument/incident_beam/incident_beam_intensity": 0.0001,
    "/entry/instrument/incident_beam/transmitted_beam_intensity": 0.0001,
    "/entry/instrument/incident_beam/ring_current": 0.0,
    "/entry/instrument/undulator_1/gap": 1.0,
    "/entry/instrument/undulator_1/energy": 1.0,
    "/entry/instrument/undulator_2/gap": 1.0,
    "/entry/instrument/undulator_2/energy": 1.0,
    "/entry/instrument/monochromator/energy": 1.0,
    "/entry/instrument/monochromator/wavelength": 1.0,
    "/entry/instrument/attenuator_1/attenuator_transmission": 1.0,
    "/entry/instrument/attenuator_1/attenuator_index": 1,
    "/entry/instrument/attenuator_2/attenuator_transmission": 1.0,
    "/entry/instrument/attenuator_2/attenuator_index": 1,
    "/entry/instrument/beam_stop/x_position": 1.0,
    "/entry/instrument/beam_stop/y_position": 1.0,
    "/entry/instrument/beam_stop/size": 1.0,
    "/entry/instrument/datamanagement/workflow_name": "boost_corr workflow",
    "/entry/instrument/datamanagement/workflow_version": "0.0.1",
    "/entry/instrument/datamanagement/workflow_kwargs": """{"key": "value"}""",
    "/entry/instrument/bluesky/scan_id": 1,
    "/entry/instrument/bluesky/bluesky_version": "1.0.0",
    "/entry/instrument/bluesky/bluesky_plan": "mesh_scan",
    "/entry/instrument/bluesky/bluesky_plan_kwargs": "mesh_scan_sample_kwargs",
    "/entry/instrument/bluesky/parent_folder": "/path/to/the/parent/folder",
    "/entry/instrument/bluesky/spec_file": "/path/to/this/spec_file_name",
    "/entry/instrument/slits_1/vertical_gap": 1.0,
    "/entry/instrument/slits_1/vertical_center": 0.0,
    "/entry/instrument/slits_1/horizontal_gap": 1.0,
    "/entry/instrument/slits_1/horizontal_center": 0.0,
    "/entry/sample/short_description": "Short sample description",
    "/entry/sample/full_description": "Full sample description",
    "/entry/sample/position_x": 1.0,
    "/entry/sample/position_y": 1.0,
    "/entry/sample/position_z": 1.0,
    "/entry/sample/position_rheo_x": 1.0,
    "/entry/sample/position_rheo_y": 1.0,
    "/entry/sample/position_rheo_z": 1.0,
    "/entry/sample/qnw_lakeshore": 1.0,
    "/entry/sample/qnw1_temperature": 1.0,
    "/entry/sample/qnw1_temperature_set": 1.0,
    "/entry/sample/qnw2_temperature": 1.0,
    "/entry/sample/qnw2_temperature_set": 1.0,
    "/entry/sample/qnw3_temperature": 1.0,
    "/entry/sample/qnw3_temperature_set": 1.0,
    "/entry/sample/rheometer_shear_rate": 1.0,
    "/entry/sample/rheometer_temperature": 1.0,
    "/entry/user/name": "John Doe",
    "/entry/user/email": "JohnDoe@mail.edu",
    "/entry/user/institution": "Institution Name",
    "/entry/user/cycle": "2025-1",
    "/entry/user/proposal_id": "none",
}
